Added Japanese localization.
Darktide-Mod-Framework/Darktide-Mod-Framework pull request #35
Opened 2023-04-13 15:44 UTC by zombine04

2023-04-14 12:52 UTC, sclu1034 requested changes

2023-04-14 12:52 UTC, sclu1034 commented on dmf/localization/dmf.lua
> +         "-- 直前 --\n1つ前の履歴が重複する場合、それを削除します。\n\n" ..
The `1` after the line break looks out-of-place.

2023-04-15 02:04 UTC, zombine04 commented on dmf/localization/dmf.lua
> +         "-- 直前 --\n1つ前の履歴が重複する場合、それを削除します。\n\n" ..
I thought `previous entry` means just one before, so I translated it to `1つ前`. Is that incorrect?

2023-04-17 08:25 UTC, zombine04 commented on dmf/localization/dmf.lua
> +         "-- 直前 --\n1つ前の履歴が重複する場合、それを削除します。\n\n" ..
Any way, I've updated the translation to match its title.

2023-04-17 09:33 UTC, sclu1034 commented on dmf/localization/dmf.lua
> +         "-- 直前 --\n1つ前の履歴が重複する場合、それを削除します。\n\n" ..
> I thought `previous entry` means just one before, so I translated it to `1つ前`. Is that incorrect?

If you do normally use literal numbers for this in Japanese, that's fine.
I guess I'm just used to languages having a dedicated word for "previous" and assumed that the `1` might just be an unrelated typo.

2023-04-17 12:10 UTC, zombine04 commented on dmf/localization/dmf.lua
> +         "-- 直前 --\n1つ前の履歴が重複する場合、それを削除します。\n\n" ..
It was not a typo, but it's fine without the `1`.

2023-04-25 21:40 UTC, merged